import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      boxShadow: {
        'glow-blue': '0 0 20px 0 hsl(var(--fintech-blue-accent) / 0.3)', // Soft blue glow
        'glow-orange': '0 0 20px 0 hsl(var(--fintech-orange-accent) / 0.3)', // Soft orange glow
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // New custom colors for the vibrant dark fintech theme
        fintech: {
          'background-light': 'hsl(var(--fintech-background-light))',
          'background-offwhite': 'hsl(var(--fintech-background-offwhite))',
          'text-dark': 'hsl(var(--fintech-text-dark))',
          'text-muted': 'hsl(var(--fintech-text-muted))',
          'blue-soft': 'hsl(var(--fintech-blue-soft))',
          'blue-accent': 'hsl(var(--fintech-blue-accent))',
          'cyan-light': 'hsl(var(--fintech-cyan-light))',
          'green-success': 'hsl(var(--fintech-green-success))',
          'border-light': 'hsl(var(--fintech-border-light))',
          'card-light': 'hsl(var(--fintech-card-light))',
          'peach-background': 'hsl(var(--fintech-peach-background))',
          'orange-accent': 'hsl(var(--fintech-orange-accent))',
          'dark-bg': 'hsl(var(--fintech-dark-bg))',
          'gradient-blue-start': 'hsl(var(--fintech-gradient-blue-start))',
          'gradient-blue-end': 'hsl(var(--fintech-gradient-blue-end))',
          'gradient-purple-start': 'hsl(var(--fintech-gradient-purple-start))',
          'gradient-purple-end': 'hsl(var(--fintech-gradient-purple-end))',
          'gradient-pink-start': 'hsl(var(--fintech-gradient-pink-start))',
          'gradient-pink-end': 'hsl(var(--fintech-gradient-pink-end))',
          'gradient-cyan-start': 'hsl(var(--fintech-gradient-cyan-start))',
          'gradient-cyan-end': 'hsl(var(--fintech-gradient-cyan-end))',
          'star-yellow': 'hsl(var(--fintech-star-yellow))',
          'dark-purple-bg': 'hsl(var(--fintech-dark-purple-bg))',
          'topup-line': 'hsl(var(--fintech-topup-line))',
          'topup-gradient-start': 'hsl(var(--fintech-topup-gradient-start))',
          'topup-gradient-end': 'hsl(var(--fintech-topup-gradient-end))',
          'card-pink-start': 'hsl(var(--fintech-card-pink-start))',
          'card-pink-end': 'hsl(var(--fintech-card-pink-end))',
          'card-purple-start': 'hsl(var(--fintech-card-purple-start))',
          'card-purple-end': 'hsl(var(--fintech-card-purple-end))',
          'card-blue-start': 'hsl(var(--fintech-card-blue-start))',
          'card-blue-end': 'hsl(var(--fintech-card-blue-end))',
          'card-darkblue-start': 'hsl(var(--fintech-card-darkblue-start))',
          'card-darkblue-end': 'hsl(var(--fintech-card-darkblue-end))',
          'phone-bg-blue': 'hsl(var(--fintech-phone-bg-blue))',
          'phone-text-blue': 'hsl(var(--fintech-phone-text-blue))',
          'phone-star-yellow': 'hsl(var(--fintech-phone-star-yellow))',
          'simulator-card-bg': 'hsl(var(--fintech-simulator-card-bg))',
          'card-dark-purple': 'hsl(var(--fintech-card-dark-purple))',
          'card-dark-red-purple': 'hsl(var(--fintech-card-dark-red-purple))',
          'button-gradient-start': 'hsl(var(--fintech-button-gradient-start))',
          'button-gradient-end': 'hsl(var(--fintech-button-gradient-end))',
          'dark-bg-lighter': 'hsl(var(--fintech-dark-bg-lighter))',
          'header-bg': 'hsl(var(--fintech-main-bg))',
          'header-text': 'hsl(var(--fintech-header-text))',
          'hero-dark-bg': 'hsl(var(--fintech-main-bg))',
          'card-mockup-purple': 'hsl(var(--fintech-card-mockup-purple))',
          'card-mockup-blue': 'hsl(var(--fintech-card-mockup-blue))',
          'card-mockup-pink': 'hsl(var(--fintech-card-mockup-pink))',
          'card-chip-yellow': 'hsl(var(--fintech-card-chip-yellow))',
          'card-chip-light': 'hsl(var(--fintech-card-chip-light))',
          'dot-pattern': 'hsl(var(--fintech-dot-pattern-new))',
          'scroll-indicator-bg': 'hsl(var(--fintech-scroll-indicator-bg))',
          dashboard: {
            'bg': 'hsl(var(--fintech-dashboard-bg))',
            'sidebar-bg': 'hsl(var(--fintech-dashboard-sidebar-bg))',
            'card-bg': 'hsl(var(--fintech-dashboard-card-bg))',
            'text-primary': 'hsl(var(--fintech-dashboard-text-primary))',
            'text-secondary': 'hsl(var(--fintech-dashboard-text-secondary))',
            'accent-blue': 'hsl(var(--fintech-dashboard-accent-blue))',
            'accent-green': 'hsl(var(--fintech-dashboard-accent-green))',
            'accent-red': 'hsl(var(--fintech-dashboard-accent-red))',
            'border': 'hsl(var(--fintech-dashboard-border))',
            'input-bg': 'hsl(var(--fintech-dashboard-input-bg))',
            'chart-bar-1': 'hsl(var(--fintech-dashboard-chart-bar-1))',
            'chart-bar-2': 'hsl(var(--fintech-dashboard-chart-bar-2))',
            'progress-bg': 'hsl(var(--fintech-dashboard-progress-bg))',
            'progress-fill': 'hsl(var(--fintech-dashboard-progress-fill))',
            'logout-button-bg': 'hsl(var(--fintech-dashboard-logout-button-bg))',
            'logout-button-hover': 'hsl(var(--fintech-dashboard-logout-button-hover))',
          },
          'light-blue-card': 'hsl(var(--fintech-light-blue-card))',
          'dark-card-bg': 'hsl(var(--fintech-dark-card-bg))',
          'dark-card-bg-secondary': 'hsl(var(--fintech-dark-card-bg-secondary))',
          'dark-text-primary': 'hsl(var(--fintech-dark-text-primary))',
          'dark-text-muted': 'hsl(var(--fintech-dark-text-muted))',
          'icon-orange': 'hsl(var(--fintech-icon-orange))',
          'icon-gray-bg': 'hsl(var(--fintech-icon-gray-bg))',
          'phone-bg': 'hsl(var(--fintech-phone-bg))',
          'phone-border': 'hsl(var(--fintech-phone-border))',
          'phone-text': 'hsl(var(--fintech-phone-text))',
          'india-white': 'hsl(var(--fintech-india-white))',
          'main-bg': 'hsl(var(--fintech-main-bg))',
          'dot-pattern-new': 'hsl(var(--fintech-dot-pattern-new))',
          'button-primary-gradient-start': 'hsl(var(--fintech-button-primary-gradient-start))',
          'button-primary-gradient-end': 'hsl(var(--fintech-button-primary-gradient-end))',
          'newsletter-orange-bg': 'hsl(var(--fintech-newsletter-orange-bg))',
          'newsletter-bird-yellow': 'hsl(var(--fintech-newsletter-bird-yellow))',
          'newsletter-bird-black': 'hsl(var(--fintech-newsletter-bird-black))',
          'newsletter-envelope-blue': 'hsl(var(--fintech-newsletter-envelope-blue))',
          'newsletter-cloud-white': 'hsl(var(--fintech-newsletter-cloud-white))',
          'newsletter-cloud-lightblue': 'hsl(var(--fintech-newsletter-cloud-lightblue))',
          'loan-card-purple': 'hsl(var(--fintech-loan-card-purple))',
          'loan-card-purple-darker': 'hsl(var(--fintech-loan-card-purple-darker))',
          'loan-card-purple-darkest': 'hsl(var(--fintech-loan-card-purple-darkest))',
          'loan-card-blue': 'hsl(var(--fintech-loan-card-blue))',
          'loan-card-blue-darker': 'hsl(var(--fintech-loan-card-blue-darker))',
          'loan-card-blue-darkest': 'hsl(var(--fintech-loan-card-blue-darkest))',
          'loan-card-green': 'hsl(var(--fintech-loan-card-green))',
          'loan-card-green-darker': 'hsl(var(--fintech-loan-card-green-darker))',
          'loan-card-green-darkest': 'hsl(var(--fintech-loan-card-green-darkest))',
          'popular-badge-bg': 'hsl(var(--fintech-popular-badge-bg))',
        }
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: {
            height: "0",
          },
          to: {
            height: "var(--radix-accordion-content-height)",
          },
        },
        "accordion-up": {
          from: {
            height: "var(--radix-accordion-content-height)",
          },
          to: {
            height: "0",
          },
        },
        blob: {
          "0%": {
            transform: "translate(0px, 0px) scale(1)",
          },
          "33%": {
            transform: "translate(30px, -50px) scale(1.1)",
          },
          "66%": {
            transform: "translate(-20px, 20px) scale(0.9)",
          },
          "100%": {
            transform: "translate(0px, 0px) scale(1)",
          },
        },
        'float-up-down': {
          '0%, 100%': { transform: 'translateY(0) translateX(0) scale(1)' },
          '25%': { transform: 'translateY(-10px) translateX(5px) scale(1.05)' },
          '50%': { transform: 'translateY(0px) translateX(-5px) scale(0.95)' },
          '75%': { transform: 'translateY(10px) translateX(5px) scale(1.05)' },
        },
        'float-left-right': {
          '0%, 100%': { transform: 'translateX(0) translateY(0) scale(1)' },
          '25%': { transform: 'translateX(-10px) translateY(5px) scale(1.05)' },
          '50%': { transform: 'translateX(0px) translateY(-5px) scale(0.95)' },
          '75%': { transform: 'translateX(10px) translateY(5px) scale(1.05)' },
        },
        'card-float-1': {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '33%': { transform: 'translateY(-10px) rotate(2deg)' },
          '66%': { transform: 'translateY(5px) rotate(-1deg)' },
        },
        'card-float-2': {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '33%': { transform: 'translateY(10px) rotate(-2deg)' },
          '66%': { transform: 'translateY(-5px) rotate(1deg)' },
        },
        'card-float-3': {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '33%': { transform: 'translateY(-8px) rotate(1deg)' },
          '66%': { transform: 'translateY(7px) rotate(-2deg)' },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        blob: "blob 7s infinite",
        'float-up-down': 'float-up-down 15s ease-in-out infinite',
        'float-left-right': 'float-left-right 18s ease-in-out infinite',
        'card-float-1': 'card-float-1 10s ease-in-out infinite',
        'card-float-2': 'card-float-2 12s ease-in-out infinite',
        'card-float-3': 'card-float-3 11s ease-in-out infinite',
      }
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;